### ISSUE TITLE
protobuf suggestion - use event type default

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#100]
If we consider that:
- the `type` field is mandatory in CoT events
- statistically, `type=a-f-G-U-C` represents nearly 2/3 (possibly even more)* of all forwardable event types

It should be possible to use the following convention:
- when encoding XML to protobuf:
  - if the `type` field is empty or absent, **drop** the XML message as invalid CoT
  - if `type=a-f-G-U-C`, **do not include** a `type` field in the protobuf at all
  - otherwise, include the `type` field literally, the way it's done currently
- when decoding protobuf to XML:
  - if `type` field is present in protobuf, transfer literally to XML
  - if `type` field is absent, set `type=a-f-G-U-C` in XML

Considering that the 'a-f-G-U-C` string is 9 bytes + 2 protobuf overhead, this will result in an 11-byte saving in more than 2/3 of the cases, with no negative impact on the other 1/3.

 *source: [personal research](https://gist.github.com/a-f-G-U-C/77fed4e7aea38e27f3c50583e840a35b)

**Comment by paulmandal** [comment]
https://github.com/paulmandal/libcotshrink/pull/13
