### ISSUE TITLE
New "team color" field in Meshtastic NODEINFO

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#107]
As of merged PR https://github.com/meshtastic/Meshtastic-protobufs/pull/33 , the Meshtastic `User` protobuf (used in NODEINFO messages) contains a new field named `team` which can be set to any of the 14 colors in the ATAK team color palette.

This can be used to persistently assign different team colors to standalone tracker devices, instead of a single color configured in the Forwarder plugin, as we do now.

Full support of the new field is still WIP; should become available in the next couple of weeks.

**Comment by a-f-G-U-C** [comment]
UPDATE: this is now fully supported in the meshtastic-device master branch

**Comment by paulmandal** [comment]
Added in: https://github.com/paulmandal/atak-forwarder/pull/114/files#diff-3d4b3256418b9752553d54cfc4a51acca779f1b434c926988c602614bd8b5336R207

**Comment by paulmandal** [comment]
Closing since there are no updates.
