### ISSUE TITLE
Binary release still current? 

### ISSUE THREAD

**Issue by jaykayenn** [paulmandal/atak-forwarder#109]
Hi, is the plugin binary in Gdrive still current? I can't get it to work for the life of me. 
Meshtastic firmware: 1.2.45
Meshtastic app: 1.2.31
ATAK: 4.4.0.2

It will connect and setup the channel, but nodes won't see each other. Both my test EUDs keep showing "x repeated errors..." ie. all received packets are in error. Even the Meshtastic app won't talk/see each other any more outside of ATAK, despite the channel setup seemingly correct. Meshtastic worked correctly prior to running the plugin on ATAK. 

What am I missing?

**Comment by paulmandal** [comment]
Try a different speed / mode, I have had similar issues using some of the modes before.

**Comment by jaykayenn** [comment]
I've switched to Medium and it worked... for about 5 minutes. Then they stopped talking to each other again. 

The worrying thing is, even after I close ATAK and change channels/device ID in Meshtastic app, the same issue persists in Meshtastic itself. Lights are blinking as normal and app shows devices are connected via Bluetooth, but text messages fail instantly. I can't say for sure of course, but it seems that something about using the ATAK plugin has caused something to change in Meshtastic. Flashing the device firmware again fixes it. I've done this whole sequence twice now and reproduced the same problem. 

Unfortunately I'm not familiar with development and don't know how to access logcat. No idea where the problem lies. Maybe I should post this on Meshtastic forum as well?

**Comment by paulmandal** [comment]
I've uploaded a beta build of 1.0.2 to the Drive link under the `beta/` folder, could you try it out and let me know if it fixes the issue?

**Comment by jaykayenn** [comment]
Here's my report for 1.0.2:

Starting again with freshly flashed TBEAMS, all was well using Medium range mode. When I tried to change to Long mode, again they stopped talking (100% message error). Meshtastic app shows correct channel info and connected, but no messages getting through. 

Resetting the channel in Mesh app to default allows the app to work and exchange messages again, but then ATAK forwarder stops working completely. As in, setting a new channel via ATAK will never get any messages any more. 

Just as I'm writing this, I tried it again and now ATAK forwarder doesn't even generate a complete QR image any more. The front and end of the URL is missing a lot of bytes. I checked ATAK and I'm now on 4.4.0.6 apparently. 

Sorry, I don't know how to help this situation.

**Comment by paulmandal** [comment]
There is a new release, 1.0.4, that may be worth trying out, please let me know how it goes.

**Comment by jeremybox** [comment]
I am seeing the same issues on the latest releases.  I would be happy to do any requested troubleshooting.  I have access to 3 android devices and 4 t-beams.

**Comment by paulmandal** [comment]
Closing since there are no updates here.
