### ISSUE TITLE
Meshtastic 1.3

### ISSUE THREAD

**Issue by mc-hamster** [paulmandal/atak-forwarder#119]
Hey Paul!

Just a heads up.... Meshtastic 1.3 is being worked on which includes a lot of major changes, including a rewrite of how we use bluetooth. Part of this is a rework of the protos.

Please be aware that when 1.3 comes out in beta, it's very likely you'll have compatibility issues and may need to have some version detection. 

1.3 has no plans for backward compatibility with 1.2.

When 1.3 goes live and out of beta, it will be called 2.0.

Cheers!

**Comment by diamondbarcode** [comment]
I am 2nd on this, that as now ATK beta version also not working with atak-forwarder i am not sure what else ATAK change but 1 of my phone run beta channel in all APP is not work anymore.

**Comment by sachaw** [comment]
Another thing we would like to change is removing the team property from each nodes information. This kind of data should be contained within its plugin messages and not be a global property.

**Comment by mc-hamster** [comment]
> Another thing we would like to change is removing the team property from each nodes information. This kind of data should be contained within its plugin messages and not be a global property.

Good point. Totally forgot about that. Maybe we can include something as an alternative general purpose grouping method.

**Comment by paulmandal** [comment]
>Please be aware that when 1.3 comes out in beta, it's very likely you'll have compatibility issues and may need to have some version detection.

I'll likely just make newer versions only compatible with 1.3+

Thanks for the heads up, I've started working on updating my integration here: https://github.com/paulmandal/atak-forwarder/pull/120 I'll try to get this out soon after 1.3 is released.

**Comment by paulmandal** [comment]
> Another thing we would like to change is removing the team property from each nodes information. This kind of data should be contained within its plugin messages and not be a global property.

This is the `Team` field, right? In my use case I only use this for Tracker devices (not connected to an EUD, but shows up in ATAK, uses the position app and nodeinfo apps). The field alone doesn't really satisfy my needs since each Tracker has a Team and Role. For now I put these into the `shortName` field but if there were a misc or grouping field I could put the data there.

**Comment by sachaw** [comment]
I'd say the best way to handle this is to have the ATAK portnum return a message containing a oneof then you can have several payload types for your various needs.
There are examples of this all throughout the existing protobufs

**Comment by paulmandal** [comment]
Closing this because we're on 2.0 now: https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1
