### ISSUE TITLE
"Comm device disconnected" and changes in ATAK are not implemented despite Meshtastic app is connected.

### ISSUE THREAD

**Issue by Copper274** [paulmandal/atak-forwarder#122]
Hey Paul,
this is my first GitHub issue entry so please excuse possible mistakes.
Tbeam module is running fine and connects with mashtastic app, all options are available.
Module shows up in plugin settings and if channel name, mode/speed or PSK is changed in ATAK the device restarts but changes are not implemented.
The @ stays red and the message mentioned above shows up every ATAK start.
I found a similar case in the closed issues with the remark that the version was not supported, same case here?
Thanks in advance.

Meshtastic firmware version: 1.2.59.d81c1c0
Meshtastic app version: 1.2.61
ATAK version: v4.6.0.4 (72eb2c83) [playstore]
Plugin version: 1.0.6-1-4.6.0
Samsung S9 Android version: 10

**Comment by Copper274** [comment]
Thank you for the remarkable quick reply.
After downgrading the app and firmware the @ turned green.
Turns out “read the fucking manual” has something to it after all.
However, if I make changes in ATAK, errors start to count up and the @ turns grey. With no channel changes its stays green.
Once again thank you for the super quick help and keep up your incredible work.

**Comment by paulmandal** [comment]
Are the devices close together? Some people have had issues when they're in the same room or part of a house

**Comment by Copper274** [comment]
Yes, the devices were close together. However, the pair mentioned in the first post also produces these errors when alone in a separate channel. An outdoor test is planned for the coming days.

To the edit question, yes all option changes like channel name, PSK letter and range/speed show up on in LCD display on the module.

**Comment by Copper274** [comment]
Update:
The test was successful. The connection was stable besides a few occasional errors.
Distance could to be one factor since models close together seemed to produce more errors.
Text chat, point and location transmission as well as moving direction indication worked well except a couple gps shortcomings of the Samsung S6 which are most likely due to the old hardware.

First device pair:
Meshtastic firmware version: 1.2.59.d81c1c0
Meshtastic app version: 1.2.61
ATAK version: v4.6.0.4 (72eb2c83) [playstore]
Plugin version: 1.0.6-1-4.6.0
Samsung S9 Android version: 10

Second device pair:
Meshtastic firmware version: 1.2.59.d81c1c0
Meshtastic app version: 1.2.61
ATAK version: v4.6.0.4 (72eb2c83) [playstore]
Plugin version: 1.0.6-1-4.6.0
Samsung S6 Android version: 7

Chanel settings:
Short/Fast
QR transmission through ATAK


I will continue testing regarding range/speed settings and actual distance between the devices.

**Comment by Artori-kun** [comment]
Hi @paulmandal , I'm having the same issue as @Copper274. The marker for the device still shows up on the map as the device receives GPS signal, but when i touch the marker, i cannot select the contact option. My settings are:

Meshtastic firmware: 1.2.64.fc48fcd
Meshtastic app: 1.2.64
ATAK version: v4.5.1.8 (4dff7717)[playstore]
Plugin version: 1.0.6-1-4.5.1

Please tell me how can i fix this. Thanks in advance.

**Comment by paulmandal** [comment]
Try the latest plugin, version 1.1.0, and let me know if it works. If your device is showing as disconnected try:

- restarting the Meshtastic device
- restart ATAK
- re-pairing
- restarting your phone

check if it works between each of those, usually just restarting the Meshtastic device gets things going

**Comment by Artori-kun** [comment]
Thanks, I installed the latest plugin as you recommended and it worked. However, when I scan the QR code to set the channel, it doesn't scan at all. Is it a bug or am I doing it wrong? Is there other way to join devices into the same channel?
