### ISSUE TITLE
Local Device Not Found

### ISSUE THREAD

**Issue by Dr1u23m** [paulmandal/atak-forwarder#126]
ATAK forwarder wont install. When I try to, it asks to update the forwarder and then kicks me out. I'm assuming it has to do with the "local device not installed" any suggestions would help
![Screenshot_20220510-111558_ATAK](https://user-images.githubusercontent.com/105298240/167663868-7b289a3a-17ea-4650-91e5-d8b5347c86b8.jpg)

**Comment by ki6uve** [comment]
I'm having the same/similar issue.  I have the ATAK-CIV 4.6.1 version installed from Playstore and Forwarder plugin 1.0.7 copied to the "custom" folder under ATAK/support/APKs but it will not install.  It runs through the install process and seems to complete but still shows "not installed" under the plugins tab in ATAK.  Tried it on an identical phone setup with the same failure.  Not sure how to proceed.

**Comment by paulmandal** [comment]
@Dr1u23m are you also using the Play Store version of ATAK? I'm installing via `adb`, I'll try to reproduce the issue in the next couple days.

**Comment by ki6uve** [comment]
Yes, the Play Store version.  Also tried downgrading to 4.5.1 with the corresponding Forwarder versions and I get an "incompatible" message under the ATAK plugins tab for the Forwarder that states I need version 4.6.1 of ATAK.

**Comment by paulmandal** [comment]
This seems to be happening with the latest Play Store release, the TAK.gov version of 4.6.1 works but I'm getting the same behavior where the plugin "installs" but doesn't actually show up as being installed. For @ki6uve you need to downgrade the plugin version too, if you're getting the incompatible message you are likely still using the version of the plugin for 4.6.1.

**Comment by paulmandal** [comment]
So word is this is happening with plugins in general (or maybe 3rd party ones?) with the latest Play Store version of ATAK. IMO installing from TAK.gov and disabling auto-update is the way to go since 3rd party plugins like the Forwarder aren't usually available right after an ATAK release.

**Comment by ki6uve** [comment]
So, just to be clear, what is the latest working option?  Tak.gov v.4.5.1 with forwarder 1.06 or is 1.07 working ok with tak.gov v.4.5.1 ?

**Comment by Dr1u23m** [comment]
@paulmandal I just wanted to take a second to say thank you.  I followed your steps and it's all working now.

**Comment by paulmandal** [comment]
Thank you! I hope the plugin meets your needs!

**Comment by ki6uve** [comment]
Big thanks from me too...the .gov 4.6.1 ATAK version and 1.0.7 plug-in have been up and running all day with zero failures.
