### ISSUE TITLE
ITAK

### ISSUE THREAD

**Issue by lycaon42** [paulmandal/atak-forwarder#129]
Are you thinking of making a version for an iTAK-Forwarder?
I'm trying to set up an entirely IOS dependant system and was pleased to see TAK made an IOS version.
If not is there a way to make this work for that application.

**Comment by paulmandal** [comment]
I don't have any plans for an iOS version at this time. I don't have a MacOS computer to do iOS development on. I'm also not sure if iTAK has plugins.

**Comment by lordmorgul** [comment]
iTAK does not support plugins, and may never while it is part of the Apple App Store since that is disallowed.  If they removed the app from the store and deployed only through TestFlight then they could do it, but that is a step backward and probably won't.
