### ISSUE TITLE
Unable to Install ATAK forwarder

### ISSUE THREAD

**Issue by KB1911** [paulmandal/atak-forwarder#130]
I have atak v4.6.1.3
plugin api: 4.6.1.civ

Hi I am able to download the Plugin but unable to install it? Any reason why?

![image](https://user-images.githubusercontent.com/106634201/171301476-60b8da33-abec-46e7-981b-0049c3e3b124.jpeg)

![image](https://user-images.githubusercontent.com/106634201/171301651-9cb8a3da-6127-44ee-8d27-b55e5e3732ea.jpeg)

**Comment by paulmandal** [comment]
Can you get a stack trace for this crash from the Android debug logs? You will need to install Android Studio or adb: https://developer.android.com/studio/command-line/logcat

**Comment by KB1911** [comment]
Is this an app that i DL from the Play Store or DL online? I am not seeing a file to click on for Logcat? Thank You.

**Comment by KB1911** [comment]
Is this something I can download from
the playstore onto my android? i dont have access to a computer.

Sent on my iphone

On Jun 4, 2022, at 19:30, paulmandal ***@***.***> wrote:

﻿

Can you get a stack trace for this crash from the Android debug logs? You will need to install Android Studio or adb: https://developer.android.com/studio/command-line/logcat<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Fcommand-line%2Flogcat&data=05%7C01%7C%7Ce71f47c2868941d5daf008da46478ce5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637899570363702755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rMo0%2FHTTnBJfzl35MTyPx2S%2Bt7qXS0X8PVqgubFosLs%3D&reserved=0>
