### ISSUE TITLE
ATAK not installing ATAK-forwarder plugin, never receives android.intent.action.PACKAGE_ADDED

### ISSUE THREAD

**Issue by HikerScott** [paulmandal/atak-forwarder#131]
On my Samsung S20 FE running Android 12 security patch May 1, 2022, when I go to install the ATAK-forwarder plugin from within ATAK it successfully installs, but the ATAK never acknowledges the installation.

Comparing the installation against a phone where it does work
ApkUpdateReceiver never receives the onReceive: android.intent.action.PACKAGE_ADDED 

Note, I have installed other plugins such as WASP, and the package added has been received.  I've uninstalled and reinstalled forwarder, have used previous versions of forwarder, attempted older versions of ATAK along with aligned older versions of forwarder, all with no luck.

Attached is a clean start and attempted install.  It's hard to show the _missing_ log entry, but I'm sure you know better than myself what to look for.
[logcat6.txt](https://github.com/paulmandal/atak-forwarder/files/8811033/logcat6.txt)

**Comment by 0ddBall** [comment]
I have the same issue on a OnePlus Nord N200 running ATAK 4.6.1.3 where Forwarder installs successfully but fails to be available or show as installed in the plugin section. Happy to provide logs if you can give me some direction.

**Comment by 0ddBall** [comment]
@paulmandal Do you have a Patreon or Venmo I can contribute to you on? This is such a critical plugin, I'd love to help defer expenses.

**Comment by jbutler988** [comment]
Bump,
I too am having the same issue. When attempting to install the plugin, it prompts me to update the plugin.

**Comment by paulmandal** [comment]
Hey all, are you using the Play Store version of ATAK? there have been some issues with plugins showing up in that version.

@0ddBall thank you! If you'd like to send me some cash you can use this link: https://www.paypal.com/paypalme/paypaulmandal

**Comment by jbutler988** [comment]
> Hey all, are you using the Play Store version of ATAK? there have been some issues with plugins showing up in that version.
> 
> @0ddBall thank you! If you'd like to send me some cash you can use this link: https://www.paypal.com/paypalme/paypaulmandal

I am using playstore version while we work on testing. I am working on setting up a self-signed setup but its on the back burner at the moment.

**Comment by paulmandal** [comment]
Can you use the version from TAK.gov? Some users have reported issues loading the plugin in the Play Store version since 4.6.1.x.

Another fix may be to hit the refresh button in Package Management in ATAK.

The last thing I've seen reported as a fix is to import the plugin through ATAK.

**Comment by jbutler988** [comment]
I will give it a shot! Will the play store signed version of the plugin work with the tak.org apk?

**Comment by jbutler988** [comment]
I am unable to get ATAK from atak.gov. Looks like the only place to get the app is from the playstore or the github repo. Looks like its time to start stumbling through making some self signed certs.

**Comment by BorisDess** [comment]
I confirm that getting APK online doesn't work.
I downloaded it from TAK.gov.
Just create an account and click on the ressources tab, log in again, then on this new private page, you'll be able to download products going on the products tab.

**Comment by jbutler988** [comment]
> I confirm that getting APK online doesn't allow the plugins to be loaded. I tried multiple sources and version without success. Installation was successful but plugin was never activated without any error being provided. I downloaded it from TAK.gov and it worked right away. If you need some tips ; just create an account and click on the ressources tab, log in again, then on this new private page, you'll be able to download products going on the products tab.

I'm a bit confused on this one. I went through tak.gov and navigated to their github repo. I'm cloning the repo now. 

Did you download the APK from tak.gov or from their github repo?

**Comment by BorisDess** [comment]
Yes, at : https://tak.gov/products/atak-civ

**Comment by jbutler988** [comment]
> From Tak.gov, at : https://tak.gov/products/atak-civ

Thank you! I just came across it. I will reply if it works for me. Thanks for the help!

**Comment by jbutler988** [comment]
Good news. Using the tak.gov version and the playstore signed packet forwarder worked exactly as intended! Thanks everyone for the help.

**Comment by EmileSpecs** [comment]
Unable to get my hands on APK from tak.gov (I don't see how I can do that).

With the Play store version it's not working as some of the others have mentioned above, any news on why this is happening and what can be done to get it to work?

I've tried all the other suggestions from @paulmandal.

Thanks!

**Comment by paulmandal** [comment]
This version may show up in the playstore version: https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1
