### ISSUE TITLE
Cannot send messages via ATAK

### ISSUE THREAD

**Issue by Artori-kun** [paulmandal/atak-forwarder#135]
Hi Paul. I'm having this issue where i have 2 t-beam devices connected to 2 phones and i'm trying to make these phones send and receive messages via ATAK. However, when i tried to send messages via ATAK, it didnt work, or very very slow (messages were received minutes after being sent). At the same time, when i send messages via Meshtastic app, it worked perfectly. The same thing happened with other ATAK packages as well. After a while, ATAK display that the other device was disconnected.
Here are my settings:
- T-beam Firmware: 1.2.64
- ATAK version: 4.4.0
- ATAK Forwarder version: 1.1.1-4.4.0

**Comment by paulmandal** [comment]
What channel settings are you using? The slower speeds will likely take a while to send chat messages, ATAK chat messages are a lot larger than Meshtastic ones.

**Comment by Artori-kun** [comment]
i'm using the short range settings. Both fast and slow options give the same result

**Comment by paulmandal** [comment]
If you tap on the Meshtastic-like icon in the lower right corner of the screen a window will open and you can click on Logging to hopefully see more details.

**Comment by ice23st** [comment]
Hi Paul! I have the same problem. Messages in ATAK can reach several minutes. Is there a solution to this problem?

**Comment by paulmandal** [comment]
Most likely updating to Meshtastic 2.0 is the right way forward once the plugin is stable. You can try the latest here: https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1
