### ISSUE TITLE
Supported meshtastic versions

### ISSUE THREAD

**Issue by nerdygeekydork** [paulmandal/atak-forwarder#138]
The README.md mentions:

The plugin has been tested with these versions of the Meshtastic dependencies. If you run into issues try installing these versions of the Meshtastic software to resolve them.

Dependency | Version
-- | --
Meshtastic-Android | 1.2.64
Meshtastic-device | 1.2.64

but it also mentions:

Set Up Meshtastic
Flash your devices with the lastest [Meshtastic Firmware](https://github.com/meshtastic/Meshtastic-device/releases/latest) (The plugin has been tested with 1.1.5 beta, if you have issues try that version)
Install the [Meshtastic App](https://play.google.com/store/apps/details?id=com.geeksville.mesh) from the Play Store.

So which is the appropriate stable version of the firmware, 1.2.64 or 1.1.5 beta or something else (since the Play Store version is always changing)?

And does this recommendation apply to all versions of atak-forwarder or is there a minimum version of the forwarder that works with meshtastic-device 1.2.64 or 1.1.5 beta?

**Comment by cazure-n00b** [comment]
Hey, I'm having issues as well. Me and some friends will be trying out various versions of Meshtastic and ATAK and find if there's a solid solution.

We can't get the apps to work together at all. Even meshtastic standalone.

**Comment by nerdygeekydork** [comment]
Update that I've discovered, it's definitely 1.2.64. 1.1.5 beta must be an old reference that was not updated.
