### ISSUE TITLE
No others users visible inside ATAK

### ISSUE THREAD

**Issue by cazure-n00b** [paulmandal/atak-forwarder#139]
Trying to create a meshnetwork with ATAK Forwarder.
I've read every single documentation and followed the YouTube tutorial made by S2 Underground. But I can't get any meshtastic network off the ground or devices that see each other.

I used the 1.2.64 firmware and app version of Meshtastic
I tried a variety of ATAK apps and their corresponding ATAK Forwarder plugin versions.

I CAN;
- I can get the link between Meshtastic devices and the phone (cloud has a checkmark in meshtastic)
- ATAK device name is seen as well in Meshtastic
- ATAK Forwarder channel name is seen as well in Meshtastic (both devices are in Meshtastic connected to the same channel / group)

I CAN'T;
- ATAK (Forwarder) devices can't see each other inside ATAK
- I can't send a message through meshtastic in the channel to each other (will pop up and the cloud icon will have a diagonal line through it immediately)

Currently using a OnePlus 7T & a Samsung Galaxy Note 9 as test devices.

**Comment by cazure-n00b** [comment]
Trying to create a meshnetwork with ATAK Forwarder.
I've read every single documentation and followed the YouTube tutorial made by S2 Underground. But I can't get any meshtastic network off the ground or devices that see each other.

I used the 1.2.64 firmware and app version of Meshtastic
I tried a variety of ATAK apps and their corresponding ATAK Forwarder plugin versions.

I CAN; 
- I can get the link between Meshtastic devices and the phone (cloud has a checkmark in meshtastic)
- ATAK device name is seen as well in Meshtastic
- ATAK Forwarder channel name is seen as well in Meshtastic (both devices are in Meshtastic connected to the same channel / group)

I CAN'T;
- ATAK (Forwarder) devices can't see each other inside ATAK
- I can't send a message through meshtastic in the channel to each other (will pop up and the cloud icon will have a diagonal line through it immediately)

Currently using a OnePlus 7T & a Samsung Galaxy Note 9 as test devices.

**Comment by cazure-n00b** [comment]
update: ATAK Forwarder won't install on my OnePlus 7T with ATAK v4.702 (6ebfe6b4)[playstore] version.

**Comment by EmileSpecs** [comment]
> update: ATAK Forwarder won't install on my OnePlus 7T with ATAK v4.702 (6ebfe6b4)[playstore] version.

Yes, I'm having the same problem. Any ideas @paulmandal?

Thanks!

**Comment by paulmandal** [comment]
Try this release: https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1
