### ISSUE TITLE
ATAK 4.7.0.4 - playstore ATAK Forwarder 1.1.3 - 4.7.0 - Meshtastic

### ISSUE THREAD

**Issue by ndoolin** [paulmandal/atak-forwarder#141]
Attempting to setup my Meshtastic Device as a Comm Device in the ATAK Forwader Config and I am not able to see my Meshtastic Device when I setup Comm Device(Nothing is listed).  Meshtastic FW is 1.3.42 and Meshtastic App is also 1.3.42 and Meshtastic is working and passing traffic on the mesh that is setup.

**Comment by jonrau1** [comment]
@ndoolin as per the docs, you need to be on the latest version of Meshtastic 1.2.64 for both the app & firmware. On that setup it will work with 4.7.0.4 - at least it does for me.

**Comment by David2552** [comment]
@ndoolin I am running 1.2.64 on both Meshtastic app and T-Beam firmware. I side loaded ATAK Civ 4.7.0.4 and installed the Forwarder plug-in, but when I go into ATAK to load the plug-in it won't show the plug-in. It's just blank. Any ideas?

**Comment by apex2nine** [comment]
You have to copy the downloaded file too atak>support>apk then go back to atak and it should popup asking you to install. Or it will say you have the wrong version which is what is happening to me.

**Comment by paulmandal** [comment]
Try thisone https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1
