### ISSUE TITLE
Can't find forwarder plugin in the atak

### ISSUE THREAD

**Issue by fai84** [paulmandal/atak-forwarder#142]
I have installed 4.7.0 atak in my samsung s20 fe, and installed the forwarder 1.1.3. but I can't find the pulg in the atak.

**Comment by David2552** [comment]
I am currently experiencing the same issue.

**Comment by apex2nine** [comment]
Same issue here. Any word on what the solution might be?

**Comment by ccollett-github** [comment]
Same issue here as well. @paulmandal, have you determined if there is a device-specific issue here? I am using a S20 FE as well. Any help is greatly appreciated, sir!

**Comment by apex2nine** [comment]
I think the developer has abandoned the project.

**Comment by paulmandal** [comment]
nah I'm just really busy

**Comment by fai84** [comment]
thx Paulmandal, you spended your time for this project

**Comment by kreator80s** [comment]
you will need the ATAK apk from tak.gov, not the play store version.

**Comment by Josh-SMU** [comment]
Why would that be? Is the plugin looking for a hardcoded value?

**Comment by kreator80s** [comment]
> Why would that be? Is the plugin looking for a hardcoded value?
google signed the play store app? Not sure why.

**Comment by paulmandal** [comment]
Try this release: https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1
