### ISSUE TITLE
No devices appear in list

### ISSUE THREAD

**Issue by Josh-SMU** [paulmandal/atak-forwarder#146]
Identical setup with another phone, ATAK 4.7.0.4 (from tak.gov), latest Forwarder. Node is paired in Meshtastic app, on one phone ATAK sees the device list fine, on the other the list is empty and the Refresh option doesnt seem to do anything. Have reinstalled all three components and rebooted multiple times.

**Comment by paulmandal** [comment]
This is patched in 2.0.1, I'll release it sometime today.

**Comment by paulmandal** [comment]
https://github.com/paulmandal/atak-forwarder/releases/tag/2.0.1

**Comment by Josh-SMU** [comment]
This fixed it, thanks
