### ISSUE TITLE
No data forwarding from ATAK 4.7.0.4 GP to Meshtastic 2.0.6

### ISSUE THREAD

**Issue by Narkozzz** [paulmandal/atak-forwarder#147]
Hello, trying to build ATAK-mesh using Tbeam v1.1 and have no success. 

1. Android phone (10+ version)
2. ATAK-civ v4.7.0.4 Google Play 
3. ATAK-Forwarder 2.0.1-1-4.7.0 GitRelease December 19
4. Lilygo Tbeam v1.1 fw 2.0.6 beta BT connected with Meshtastic app 2.0.6

ATAK app receives only discovery broadcasts of other mesh members, no other data received. Unlike 1.1.2 plugin version, 2.0.1 dont push configuration to Tbeam. Nothing happens when Generated PSK selected, same as nothing happens if you scan QR code in ATAK. Meshtastic stays on it's pre-ATAK settings, ATAK shows new channel name in plugin status and lists discovered units.

**Comment by kreator80s** [comment]
Same here, I tried with Forwarder 2.0.1, Meshtastic 2.0.6/2.0.7, ATAK 4.7.0.4 downloaded from TAK.gov. multiple phones Samsung S8 Note 8 , Google Pixel 6.
Tbeams flashed with the latest firmware through the web flasher utility.
If ATAK is installed from the play store it crashes once you start setting any values in forwarder.

I noticed that the Tbeams will work fine with the Meshtastic app only. once you use ATAK forwarder nothing works after that and I have to flash the Tbeams again. Setting the device config in Meshtastic app after and the Tbeams still cant see each other anymore.

Q:
How do I extract the forwarder logs that I see in ATAK to post them here?
I get 0 rcvd or delivered and lots of errors.

**Comment by Josh-SMU** [comment]
I am having the same issue. ATAK 4.7.0.4 from tak.gov, forwarder 2.0.1, fw/app 2.0.6. Other members dont appear in ATAK. Any nodes I configured via ATAK I cant configure in the Meshtastic app (channel options arw blank and everything is grayed ouf/unclickable). Also, in the forwarder logging console within ATAK I see broadcasts from the other device/member and it says its in the tracker list and therefore ignored/discarded.
