### ISSUE TITLE
ATAK 4.8 support

### ISSUE THREAD

**Issue by n0p** [paulmandal/atak-forwarder#148]
I think it just got released, opening issue to track progress :)

**Comment by PhilipLykov** [comment]
I also wait for update to support ATAK 4.8

**Comment by SCWhite** [comment]
I think the new release for ATAK 4.8/ 4.8.1 still have some issue with Meshtastic 2.0.20
some how it's always disconnected.

ATAK 4.8 with correspond plugin works just fine.

**Comment by paulmandal** [comment]
https://github.com/paulmandal/atak-forwarder/releases/ 2.0.5 and later will support 4.8.0 and 4.8.1
