### ISSUE TITLE
AtakUid is null, no location sent

### ISSUE THREAD

**Issue by Josh-SMU** [paulmandal/atak-forwarder#153]
Meshtastic 2.0.14 and newest Forwarder. If device is managed by Forwarder it works, if managed by Meshtastic it does not. In the logging console, it says AtakUid=null despite being on the same channel and displaying the member name.

**Comment by paulmandal** [comment]
I'm not able to reproduce this -- I'm seeing markers with the device being managed by Meshtastic. Try clicking the "Broadcast Discovery" button and see if that sorts it out, the plugin uses that message to map ATAK UIDs to Meshtastic IDs. It may also be from having the Meshtastic app open in the background but that feels unlikely, still might be worth a try if you have it open.

**Comment by Josh-SMU** [comment]
I've hit the broadcast button a hundred times on both devices with no change.

Do you mean try NOT having Meshtastic open while ATAK is managing the device?

**Comment by Josh-SMU** [comment]
It is possible that my other issue is causing this? With the LongName ending in a special char?

It may be good to test that fix before tackling this one

**Comment by Josh-SMU** [comment]
I'll have to figure out how to set up Android Studio and test this; I might not have the bandwidth or knowledge to do this. My other thoughts are:

* Is there a difference in tx between a T-beam and a RAK? As in is the broadcast message being truncated? This would be something I should test via meshtastic cli to see what the actual message being received is. I have not done cli messgaing before but I assume it's straightforward

* The RAK4631 is the chipset being increasingly used in field/tactical applications so this may be one worth picking up and testing against going forward

**Comment by Josh-SMU** [comment]
Actually after doing more testing the plugin is failing to communicate at all. I uninstalled and reinstalled the plugin, disabled plugin manages device, conigured the channel via the Meshtastic app, and even when hitting broadcast, nothing happens, not even in the debug panel (which I have set to verbose). However in Meshtastic I can send messages to the channel and both devices get it instantly.

**Comment by Josh-SMU** [comment]
Ok I have it working now, with Meshtastic Android 2.0.14 and firmware 2.017. The versions listed in your releases blurb crash ATAK and Android 2.0.9 fails. Marking this as closed
