### ISSUE TITLE
Different Names in ATAK

### ISSUE THREAD

**Issue by Brechtl86** [paulmandal/atak-forwarder#156]
The device name in ATAK and on TBeam are different.  For example: my TBeam is called ebe4 and ATAK calls it ebe6.  This is the case with two devices and it is always the last digit.

**Comment by paulmandal** [comment]
Thanks for reporting this but it can't be fixed. T-Beams use a Bluetooth address that is 2 higher than the address used in the Meshtastic device ID. My plugin only has access to the Bluetooth address but not the device type, so I can't know whether to reduce the address by 2 or not.
