### ISSUE TITLE
reboot loop

### ISSUE THREAD

**Issue by Jamesmckain19** [paulmandal/atak-forwarder#157]
Paul, 

First, thank you for this awesome tool!  I appreciate the work you put in and shared with us.

I am having an issue when I connect my Meshtastic device (Lilygo Lora32) to the Meshtastic app, everything functions as expected.  When I run it through the ATAK forwarder, however, the meshtatic device gets caught in a reboot loop.

Do you have any thoughts or suggestions.

Thank you in advance!

**Comment by paulmandal** [comment]
If you tap on the icon in the lower right corner of ATAK (it looks kinda like a T-Beam) and go to the Logging tab do you see anything? You may want to change the logging level to Debug in the ATAK Forwarder settings.

**Comment by Jamesmckain19** [comment]
Dear Paul,

Thank you for helping with this. I have looked at the debug log. What
should I be looking for. I can tell you that when I turned on “Disable
writting to Comm Device”, the resetting loop stopped, but I wasn’t able to
communicate with the other ATAK devices.

**Comment by kjlevitz** [comment]
I am having a similar issue, everything worked before I rebooted my device.

Galaxy S10E (US)
Andriod Ver. 12
One UI Version 4.1

ATAK 4.7.04
Meshtastic 2.0.20
Forwarder 2.0.1-1

Using Meshtastic settings for channel info. 

ATAK, Mesh, and Forwarder were working fine, I restarted my phone and now ATAK constantly crashes when opening. 

`Native crash report
Timestamp = 1677257160

{"TAK.sessionid":"f92a539f-a18e-42b3-bf5a-f4fc33d09a82",
"TAK.uid":"ANDROID-a7cd05895a274198",
"timestamp":"",
"os.version":"4.14.190-23725627-abG970USQS8IVL1",
"android.release":"12",
"android.sdk":"31",
"device.model":"SM-G970U",
"device.manufacturer":"samsung",
"ACRA.version":"4.6.1",
"TAK.brand":"",
"TAK.version":"4.7.0.4 (928e13af)",
"TAK.revision":"1663372165",
"TAK.plugin-api":"",
"TAK.error":"",
"TAK.stackHash":"",
"system.plugins": [],
"plugins":[{"plugin":"plugin.version.loaded.ATAK Forwarder","version":"2.0.2 (1) - [4.7.0]-1"}
]}

[](url)
Signal caught: SIGABRT

********** Stack trace follows:

#0 - 0x705a55fb20
  stack pointer: 0x6c02db51b0
  /apex/com.android.runtime/lib64/bionic/libc.so abort
    offset = 0x51b20


********** End of stack trace`


`"TAK.error":"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference",`

`01","SEM_FIRST_SDK_INT":28,"SEM_INT":3101,"SEM_PLATFORM_INT":130100}},"BRAND":"samsung","PRODUCT":"beyond0qltesq","TOTAL_MEM_SIZE":117027876864,"AVAILABLE_MEM_SIZE":107136765952,"CUSTOM_DATA":{},"STACK_TRACE":"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference\n\tat com.paulmandal.atak.forwarder.comm.meshtastic.m.b(SourceFile:2)\n\tat com.paulmandal.atak.forwarder.comm.meshtastic.m.e(SourceFile:6)\n\tat com.paulmandal.atak.forwarder.comm.meshtastic.v.i(SourceFile:1)\n\tat com.paulmandal.atak.forwarder.comm.meshtastic.v.j(Unknown Source:0)\n\tat com.paulmandal.atak.forwarder.comm.meshtastic.g.run(Unknown Source:4)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.app.ActivityThread.main(ActivityThread.java:8663)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)\n","STACK_TRACE_HASH":"f3bd79d9","INITIAL_CONFIGURATION":`

After removing the forwarder plugin ATAK loads no issues.

**Comment by paulmandal** [comment]
The reboot loop is likely caused by the plugin writing the channel config every time, this will be patched in the next release.

**Comment by Jamesmckain19** [comment]
Thank you!  I really appriciate you.

**Comment by paulmandal** [comment]
@Jamesmckain19  No problem, I hope this fixes the issue!

**Comment by kjlevitz** [comment]
Great work, thanks for the speedy review!
I see the new version is uploaded, I'll get it set up and see if my issue repeats.

**Comment by kjlevitz** [comment]
The same problem still, unfortunately, I completely re-loaded everything, fresh installs. ATAK crashes a soon as the plugin is installed. 

Same error in the stack trace:

"TAK.error":"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference",

**Comment by paulmandal** [comment]
Can you provide the rest of the fresh stack trace and the version of ATAK
you're using please?

**Comment by kjlevitz** [comment]
Here is the full trace:

https://drive.google.com/file/d/19UPeAO4wDAgSnh1ZKVj90nWfxy7-N35V/view?usp=sharing

This was before after just updating and then after I deleted the forwarder plugin, delete meshtastic, delete ATAK, delete ATAK folder, reboot the phone, rest Meshtastic device(lora tbeam but the same issue is happening on my RAKs), and reinstall in order of Meshtastic>ATAK>Forwarder
