### ISSUE TITLE
devices shows as disconnected in ATAK 4.7  with ATAK-Plugin-ATAK.Forwarder-2.0.3-1-4.7.0-civ-release.apk

### ISSUE THREAD

**Issue by krasi-georgiev** [paulmandal/atak-forwarder#158]
4.7 atak, 
2.0.20 fw
2.0.17 androind app
tbeam and rak 4631 hardware

**Comment by paulmandal** [comment]
Thanks for the report, I am testing with some RAK devices today and will let you know if I see this.
