### ISSUE TITLE
Forwarder doesnt appear to like intermediary devices

### ISSUE THREAD

**Issue by Josh-SMU** [paulmandal/atak-forwarder#160]
Scenario: 

User1 has personal meshtastic device
User2 has personal meshtastic device
Router1 is another meshtastic device
All are on the same firmware and channel settings
Router1 is deployed halfway between User1 and User2 who are just barely out of range by themselves
Router1 is within range of both User1 and user2

Expected result: Router1 should relay messages between User1 and User2

Actual result: User1 and User2 cannot communicate

**Comment by paulmandal** [comment]
Can you validate that Meshtastic chat messages go through with this configuration? The plugin should be setting the `hopLimit` on messages to `3`.

**Comment by Josh-SMU** [comment]
Sorry, I should have updated this issue. It appears the problem is with Meshtastic itself and likely not with the Forwarder at all: https://github.com/paulmandal/atak-forwarder/issues/160

**Comment by Josh-SMU** [comment]
I will close this issue, and if the aforementioned issue is resolved but the functionality is still not working I will open a new issue here.
