### ISSUE TITLE
ATAK 4.9

### ISSUE THREAD

**Issue by hallchorn23** [paulmandal/atak-forwarder#177]
Is there an apk coming that is comparable with atak 4.9 ?

Thanks so much

**Comment by paulmandal** [comment]
Support for 4.9.x will come in the next month or so, after which the plugin won't support earlier versions anymore.

**Comment by DarkFIxED** [comment]
Hello! Do you have any ETA for now?

**Comment by Tahkis** [comment]
Could we have a compiled version of Forwarder 2.0.7 for ATAK 4.8.1? Currently the latest release only supports up to ATAK 4.7.  Or was there some particular reason why the 4.8.1 release of 2.0.7 does not exist?

Btw, when do you think you would be able to get the Forwarder 2.0.8 supporting ATAK 4.9 out? Will that also support ATAK 4.8.1 then?

**Comment by SCWhite** [comment]
@Tahkis  I think you missed the part from the 2.0.7 release note
```
For now the plugin will not support ATAK versions after 4.7.0.x. The plugin API changed in 4.9.x and I don't 
want to maintain two versions of the plugin codebase for now, so likely we will migrate to the new plugin API 
in the next month or so. There is also an issue in later versions where the plugin cannot connect to the 
Meshtastic service that I need to sort out before supporting those versions.
```

I know people love this project, but have some patience

**Comment by Tahkis** [comment]
Hi Paul,
No problem, fully understand! Pitty the pipe has broken :-(

But as you said, lots of people seem to love this project :-)

If you need any help in testing I'm happy to contribute!

Cheers,
Tatu

ps. I also got the Samsung Xcover 4s QR code reader to work w/ Forwarder.
Not sure why it is so picky in scanning but requires a bit of vertical
movement over the code to scan -> makes sharing of the code possible.

pps But there clearly seems an issue in comms between the MT app and
Plugin. Eg configuring MT client using plugin does not work even in Android
11. I'm able to get the green CFG icon on but only if I conf from MT app
itself (and have the setting Plugin Manages Device = OFF). Yet no data gets
transfered over MT between ATAKs via Forw nor does the device discovery
work. And I am 100% sure the channel conf is equal in both radios. And all
this in A11 w/ ATAK 4.8.1, Forw 2.0.6 and MT 2.1.15.

**Comment by BairdGoW** [comment]
Not asking for an eta. just curious if this is still being worked on or 4.10 now that is has been released. Thank you!
