### ISSUE TITLE
ATAK Causing Reboot Loop?

### ISSUE THREAD

**Issue by MON5TER-MA5H** [paulmandal/atak-forwarder#180]
Following the latest update, I've installed 
ATAK 4.7.04, 
Forwarder 2.0.7-4.7.0, 
Meshtastic App 2.1.14 
Tbeam firmware 2.1.14.  
Calyxos Android 13. 

Everything connects at first, but the Tbeam is stuck in a constant reboot loop and then ATAK gives a repeated "ATAK isn't responding" error.  If I close ATAK, then the Tbeam stays booted.

**Comment by SCWhite** [comment]
This is a work around I believe can solve your problem.

turn off "Plugin Manages Device" option
do the configuration on Meshtastic App side
and manually keep setting same on both side.

this should prevent the reboot loop problem.

**Comment by MON5TER-MA5H** [comment]
That certainly seemed to address the boot looping on the Tbeam.  Sadly ATAK is still crashing.

**Comment by mikavdwiel** [comment]
> That certainly seemed to address the boot looping on the Tbeam. Sadly ATAK is still crashing.

I have the exact same problem, before it used to work on one of my devices, but after trying to fix it by downgrading, and then going back to the latest version of forwarder the problem also occurred on that only working device. So it could be some sort of external setup or something. All I do know is that it I can't use forwarder at all with this problem. Let me know if i allso need to do any troubleshooting steps to locate possible problems causing this.

**Comment by mikavdwiel** [comment]
@MON5TER-MA5H I have found a fix, install forwarder [v1.0.6-1-4.5.1](https://drive.google.com/file/d/1N_snQ3XBVHv6pTE1ae0bgOPdf--sh2uW/view?usp=drive_link) open atak 4.7.0 once, it will say the plugin is incompatible. Then go back and install forwarder latest version for atak 4.7.0. It will ask to update the old version of forwarder. Do this and now it works, seems like the old version left something behind that the new version needs.

**Comment by whiskas85** [comment]
It is still happening in 2.0.8
