### ISSUE TITLE
Export/Import MT channel created w/ ATAK Forwarder

### ISSUE THREAD

**Issue by Tahkis** [paulmandal/atak-forwarder#181]
User needs to be able to export and import MT channel (name+psk+type) created in ATAK Forwarder tool settings using a text string or file. This feature would allow copying channel details between terminals having Android versions not supporting QR code scanning natively.

**Comment by paulmandal** [comment]
Hey thanks for the feature request, I think this is a good idea and will add it to the next release.

**Comment by Tahkis** [comment]
Another thought: Meshtastics app itself has got a qr scanner built in (works even if the device platform camera app does not provide the reader itself). Hence embedding QR-reader library in the plugin code could do the trick too and ensure QR scan would work regardless of platform capabilities.
