### ISSUE TITLE
4.10

### ISSUE THREAD

**Issue by BairdGoW** [paulmandal/atak-forwarder#187]
Just curious if a 4.10 release is being worked on. dont need an eta. Thanks for everything!

**Comment by whiskas85** [comment]
is this project still alive?

**Comment by ibkickinit** [comment]
Cant find 2.0.5 anywhere, is there a version that willl work with 4.8.1 at least still?

**Comment by SCWhite** [comment]
@ibkickinit you can find 2.0.5 in the [previous releases](https://github.com/paulmandal/atak-forwarder/releases)
And to others, unless you're willing to contribute some code, the best thing to do is buy him a coffee and wait.
or alternatively, go try Meshtastic's ATAK plug-in [here](https://github.com/meshtastic/ATAK-Plugin)
haven't make it work though.
