### ISSUE TITLE
External GPS meshtastic board

### ISSUE THREAD

**Issue by CypressXt** [paulmandal/atak-forwarder#195]
Hey @paulmandal and @a-f-G-U-C thanks for the awesome work! 

I was wondering how the meshtastic board GPS data are handled (when configured as a `Comm Device`) ?
As far as I could see, there is no way to tell ATAK to use a meshtastic board as an external GPS provider but in the Meshtastic APP you can tell the board to broadcast its GPS position periodically as displayed bellow: 
![Screenshot_20240106-225220](https://github.com/paulmandal/atak-forwarder/assets/4773475/9a79d29d-4168-43df-8225-29f41993d695)

Is ATAK-Forwarder able to use those GPS frames broadcasted by the Meshtastic board on it's own or should we patch the atak-forwarder plugin to enable external meshtastic GPS support ?

**Comment by paulmandal** [comment]
ATAK Forwarder will treat those GPS pings as a Tracker, it will try to use the shortName to pick its icon/color. It will show them on a map. Trackers can also be configured via the plugin in the settings menu.

For devices connected to ATAK the phone GPS is going to be much more accurate unless there is a MT device with an especially nice GPS module.

**Comment by CypressXt** [comment]
Awesome, thanks a lot for the clarification !
