### ISSUE TITLE
v5.0.0 project build error 'atak-takdev-plugin' not found.

### ISSUE THREAD

**Issue by chaoz014** [paulmandal/atak-forwarder#200]
Hello,

I'm trying to build the latest release apk on Android Studio but get the error:

A problem occurred evaluating project ':app'.
> Plugin with id 'atak-takdev-plugin' not found.

I downloaded the v5.0.0.13-SDK from TAK.gov but I only see the atak-takdev-plugin Jar file not a folder or a script I can run to build it.
I also tried installing the plugin via plugin settings. I was able to build and run the hello-world app on a device, however.

Any help is appreciated.

Thanks

**Comment by paulmandal** [comment]
https://github.com/paulmandal/atak-forwarder/blob/main/app/build.gradle#L42 needs to point to the takdev JAR file
you may also need to include `sdk.path=/path/to/atak/sdk/` in your `local.properties` file

**Comment by chaoz014** [comment]
That worked like a charm.

Thank you, Paul.

**Comment by p34135092** [comment]
Hi, i meet the same problem, Plugin with id 'atak-takdev-plugin' not found.
but I downloaded the ATAK-CIV-5.2.0.10-SDK from TAK.gov but I only see the atak-gradle-takdev.jar file rather than  'atak-takdev-plugin.jar',Did Tak offical just change the file name in 5.2.0.10?

Thanks
