### ISSUE TITLE
Signing the plugin

### ISSUE THREAD

**Issue by mberezhpnw** [paulmandal/atak-forwarder#33]
Not really an issue with this app, but just having trouble figuring out how/what key to add to the AtakPluginRegistry.ACCEPTABLE_KEY_LIST when building a release version of ATAK. I tried the public key from the generated keystore that I would be using for atak-forwarder, and followed the directions from the README provided in the atak-civ plugin signing instructions, which instruct to sign with RSA and SHA1withRSA. With all of that still no luck, atak does not recognize the key. I was hoping you had successfully built a release version of atak and your atak-forwarder app, and could share some how-to steps on achieving this.
Thanks!

**Comment by paulmandal** [comment]
When I was trying to get this working I couldn't find the "right" way to get the key signature, I just modified `AtakPluginRegistry` to output the signature to `logcat` and then I copied it into the `ACCEPTABLE_KEY_LIST`.

**Comment by paulmandal** [comment]
Just a heads up -- I am going to try to get this signed by the TAK Product Center in approx 1 week after I've done some more testing with the current code.

**Comment by paulmandal** [comment]
Signed plugin is now available here: https://drive.google.com/drive/folders/1xeKJnn9tmzkkmuDbMp0LCLOV9OzHU-Ex
