### ISSUE TITLE
CoT events from Meshtastic aren't relayed back to TAK network

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#34]
The expected behaviour with external comms plugins is that the events received via the plugin are relayed by the receiving EUD to the rest of the team through all connected interfaces (tagged to avoid loopback issues), to enable communication diversity without network splits. 

Currently, inbound Meshtastic events are processed internally but not relayed via WiFi, VPN, IP multicast, TAK server etc. I suggest that they should also be relayed externally.

**Comment by paulmandal** [comment]
This should be fixed as part of https://github.com/paulmandal/atak-forwarder/pull/43
