### ISSUE TITLE
Inbound message relay using sockets instead of API methods

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#35]
Currently, the inbound message relay uses a UDP socket to feed the CoT messages into ATAK's listening port. This approach works well in the default configuration, but is not optimal and has obvious limitations.

https://github.com/paulmandal/atak-forwarder/blob/8d12d904930fba2e7995088daa4e990d19d338f2/app/src/main/java/com/paulmandal/atak/forwarder/handlers/InboundMessageHandler.java#L58

The ATAK API has built-in, protocol agnostic methods for dispatching CoT events directly. I noticed, in the ATAK source code, the following method being used for a similar purpose: 
```
import com.atakmap.android.cot.CotMapComponent;
(...)
CotMapComponent.getInternalDispatcher().dispatch(event);
```

Also, for the purpose of issue #34, `CotMapComponent.getExternalDispatcher().dispatch()` looks promising.

See: https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/ATAK/app/src/main/java/com/atakmap/comms/CotDispatcher.java

I'm sorry, I still don't have a working ATAK build environment so it's a bit of a shot in the dark.

**Comment by paulmandal** [comment]
Thanks for raising this issue! I've updated the plugin to use `CotDispatcher` to dispatch inbound CoTs.

I don't have enough phones to test whether this also fixes https://github.com/paulmandal/atak-forwarder/issues/34 but I should soon.
