### ISSUE TITLE
Incompatible altitude values from standalone meshtastic devices

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#36]
The CoT schema specifies that altitude must use the **HAE** (height above ellipsoid) model, and strongly discourages the use of the alternative **MSL** (mean sea level) model.

> MSL is empirically derived (as is AGL from DTED). MSL is based on an estimate of “sea level”
which is affected by the density of the Earth’s crust. “Sea level” is actually an irregular,
undulating surface that’s higher where the crust is densest. The shape of this surface is modeled
by a big 2-D table of measurement, an Earth Gravity Model (EGM). The model is refined
periodically [...]
> In short, MSL is an interoperability nightmare. You have to have the same model, gridding, and
interpolation to exchange information, or errors will result. All this is avoided if we use HAE.
HAE is a mathematical model with just a few parameters for ellipse axes. It’s simple, accurate,
and stable.
> (Mike Butler, 2005, *The Developer’s Guide to Cursor on Target*)

However, the meshtastic firmware is currently using the MSL model, which makes the altitude data from meshtastic devices effectively **unusable for CoT purposes**.

I have raised the issue with the meshtastic project: https://github.com/meshtastic/Meshtastic-device/issues/359

**Comment by paulmandal** [comment]
This is patched here:

https://github.com/paulmandal/atak-forwarder/blob/main/app/src/main/java/com/paulmandal/atak/forwarder/comm/meshtastic/MeshDeviceConfigurator.java#L255
