### ISSUE TITLE
Small inaccuracies in non-TAK CoT events for standalone devices

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#37]
A few small inaccuracies in the generated CoT events from standalone meshtastic devices

### 1) meshtastic-device locations are *always* gps-generated

Currently the event "how" attribute is hard-coded to **h-e** ("human-estimated"). 
https://github.com/paulmandal/atak-forwarder/blob/8d12d904930fba2e7995088daa4e990d19d338f2/app/src/main/java/com/paulmandal/atak/forwarder/nonatak/NonAtakStationCotGenerator.java#L126
In reality, the location data from meshtastic devices is either sourced from a GPS receiver, when available, or not included at all. The "how" attribute can be safely hard-coded to **m-g** ("machine-generated by GPS receiver")

Additionally, the geopoint source is hard-coded to **USER**; it should probably be **GPS**
https://github.com/paulmandal/atak-forwarder/blob/8d12d904930fba2e7995088daa4e990d19d338f2/app/src/main/java/com/paulmandal/atak/forwarder/nonatak/NonAtakStationCotGenerator.java#L151

### 2) altitude source should be GPS not DTED (but not yet)

Currently the "precision altsrc" attribute is hard-coded to **DTED0**, but the code simply passes through the altitude from the meshtastic device, which is GPS-derived. In the ideal case, the altsrc should be **GPS**. 
However since the altitude value provided by meshtastic is not CoT compatible (issue #36), in the short term the best value is probably **"???"**

See: https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/atak/MapCoreInterfaces/lib/src/main/java/com/atakmap/coremap/maps/coords/GeoPointMetaData.java

### 3) default role "RTO" is not the typical role of standalone meshtastic devices

https://github.com/paulmandal/atak-forwarder/blob/8d12d904930fba2e7995088daa4e990d19d338f2/app/src/main/java/com/paulmandal/atak/forwarder/nonatak/NonAtakStationCotGenerator.java#L155

I suggest "Team Member" as a neutral, safe default.

### 4) UIDs not sufficiently collision-proof

In general, CoT UIDs are supposed to uniquely identify individual real-world entities. For this, they need to be deterministic (same entity same UID) but also globally unique or, at least, *reasonably* collision-proof.
Currently the UID is set to the meshtastic device's `longName`, which is informational, user-specified and frequently reused across multiple devices. It is neither required nor strongly expected to be unique.

https://github.com/paulmandal/atak-forwarder/blob/8d12d904930fba2e7995088daa4e990d19d338f2/app/src/main/java/com/paulmandal/atak/forwarder/nonatak/NonAtakStationCotGenerator.java#L121

I suggest using a UID derived from the device's node ID, which in its turn is derived from the CPU's serial number or MAC address and is expected to be unique as a matter of network operation. For example: `MESHTASTIC-1234abcd`

**Comment by paulmandal** [comment]
Thank you for all the details here, I don't have much domain knowledge so this is a big help.

PR to fix these: https://github.com/paulmandal/atak-forwarder/pull/40

**Comment by a-f-G-U-C** [comment]
The PR looks great and fixes all the points in this issue. Thanks, and glad to be of assistance.
