### ISSUE TITLE
mobilinkd support!

### ISSUE THREAD

**Issue by adrianpike** [paulmandal/atak-forwarder#54]
Hey Paul, been following the project closely - super relevant to my interests and I'm really excited someone else is hacking on the same stuff I am. You've tackled a lot of the stuff I have on my feature wishlist, too.

I've got a mobilinkd TNC and would love to use it to send PLI's - right now I'm using a delightfully Rube Goldberg setup involving direwolf and netcat.

It's been a long time since I've written any Java in anger, but I'll aim to get an environment up this coming weekend. I'll probably run into questions along the way, is there a better place to throw questions your way other than here?

My first one is about what the development lifecycle looks like - is there a way to disable plugin signature checking on a build of ATAK so I can iterate, or do you have another way for iterating on plugin code? I can stub & test a bit, but I'm sure there will be a bit of testing in prod.

**Comment by paulmandal** [comment]
Hey Adrian, glad to hear you're interested in this project! You can reach me here or on the ATAK Discord if you have any questions about the codebase.

You can disable plugin signature checking in ATAK by modifying the `AtakPluginRegistry.verifySignature()` method to always return `true`.
