### ISSUE TITLE
BUG: plugin overwrites the firmware region setting (NEW)

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#59]
This one took a fair bit of debugging, but I think I found the problem.

## Background
The meshtastic firmware has recently transitioned from separate region-specific builds (US/JP/EU/etc) to a one-build-fits-all model, with the region implemented as a configuration variable.

## Currently
When running the ATAK plugin with meshtastic firmware 1.1.5+, and the region is set to a non-US value in the firmware, the region setting is being stubbornly reset by the plugin to the default (US) channel bandplan. This can place non-US users at risk.

## Steps to reproduce
- assuming tester is located in the US
- use a tbeam board with firmware >= https://github.com/meshtastic/Meshtastic-device/commit/7ef2cc86239abd5c7521adf092f2d6eef31a7c4e
- connect the tbeam board to a USB port
- (on phone) pair the board with the Android app but DO NOT open ATAK yet
- (on computer) using the python utility, change region to a non-US one in the 915MHz range (most of them are SUBSETS of the US range, so are safe to use in the US) - I use and recommend ANZ:
`meshtastic.py --debug --set region 6`
- (on computer) using a serial terminal, reboot the board via DTR pulse (Ctrl-A Ctrl-P in `picocom`) and watch the boot messages:
```
Loaded saved preferences version 11
Installing AES256 key!
legacy_region=1.0-EU, region=6, NODENUM=0xdeadbeef, dbsize=2
Wanted region 6, using ANZ
Starting meshradio init...
Set radio: name=ATAK, config=1, ch=6, power=0
Radio myRegion->freq: 916.000000
Radio myRegion->spacing: 0.500000
Radio myRegion->numChannels: 20
```
notice that the region setting is correctly honored
- (on phone) start ATAK + forwarder plugin and connect to the board
- (on computer) keep watching the messages in terminal until this line is encountered:
```
    Client is setting radio
```
- (on computer) DTR-pulse the board again and watch the boot messages:
```
Loaded saved preferences version 11
Installing AES256 key!
legacy_region=1.0-EU, region=0, NODENUM=0xdeadbeef, dbsize=3
Wanted region 0, using Unset
Starting meshradio init...
Set radio: name=ATAK, config=1, ch=0, power=0
Radio myRegion->freq: 903.080017
Radio myRegion->spacing: 2.160000
Radio myRegion->numChannels: 13
```

Notice that, at this point, the board channel plan has been reset to US (default plan if unset, but illegal in most places!) and the incorrect setting even persists across reboots - until it is manually changed with the python tool. 

## Further information
The issue does not occur when changing the channel from the Meshtastic-Android app.

**Comment by a-f-G-U-C** [comment]
Further information: the issue is not present with firmware 1.1.2, which I have reverted to.

It's also possible that this may actually be a regression in Meshtastic-device rather than a bug in atak-forwarder.

**Comment by paulmandal** [comment]
Hey this is almost definitely due to the Meshtastic protobufs being out of date, it looks like a region field was added that we don't know about so we're not retaining it when we parse/setConfig() with the older protobufs. I can fix this tonight.

**Comment by paulmandal** [comment]
Haven't been able to test this but it should work: https://github.com/paulmandal/atak-forwarder/pull/62
