### ISSUE TITLE
Usability: Poor UI rendering on WVGA / FWVGA devices

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#63]
On devices with screen resolutions between 480x800 - 480x900 the plugin's UI rendering is distorted, bordering on unusable, even though the rest of ATAK’s UI renders flawlessly even at 480x800. 

There are a few issues:

- Word-splitting in tab labels causing a multi-line effect, further reducing the usable screen area
- "Target device" label overlaps comm device fields above
- Comm device ID is overlapped by Comm toggle switch (use of a toggle switch type control is really not optimal in this context as it uses *twice the width* it really needs)
- "Set Comm Device" overlaps "Refresh" on WVGA screens
- also, on one WVGA device (not shown), the Comm Device line actually word-wraps

![Screenshot_00](https://user-images.githubusercontent.com/65810997/96338962-fd82d400-1080-11eb-8ac1-5d4806ccb070.jpeg)

- packet counters line gets "pushed" to the left outside visible area - increasingly so as the numbers grow in size
- the "Dlvd" label word-wraps

![Screenshot_01](https://user-images.githubusercontent.com/65810997/96339068-a4677000-1081-11eb-90c1-d917f56fbd39.jpeg)

- more button overlap, here "Clear Data" overlaps "Clear MsgQ" completely

![Screenshot_02](https://user-images.githubusercontent.com/65810997/96339073-aa5d5100-1081-11eb-9e47-879a2a88993b.jpeg)

**Comment by paulmandal** [comment]
This improves the UI for smaller screens by reducing some element sizes (mostly buttons) and using `ConstraintLayout`

There were some things I could not figure out (sorry not much of a UI/UX person), e.g. the Target Device spinner width, but it should be a significant improvement from the previous iteration: https://github.com/paulmandal/atak-forwarder/pull/65

**Comment by a-f-G-U-C** [comment]
There are several good improvements in PR #65 and no regressions as far as I can tell. It doesn't fix all problems, though. It should be safe to merge as-is and leave this issue open for further refinements.

**Comment by a-f-G-U-C** [comment]
Closing as no longer an issue with the new UI design
