### ISSUE TITLE
Split plugin into ATAK/Meshtastic halves?

### ISSUE THREAD

**Issue by HookdomPonix** [paulmandal/atak-forwarder#79]
I'm not sure if the ATAK product center would allow this, but have you considered splitting the Meshtastic stuff into another APK that doesn't need to go through the signing process?  

This would allow for development towards the MT half to proceed at a pace while simplifying the ATAK stuff enough that it might be possible to stay current on the signing process.  

Also, thanks for this great project.  Once everything stabilizes some both here and in Meshtastic I think this is going to become a premier use case for ATAK and MT.

**Comment by paulmandal** [comment]
I doubt they'd let the plugin load and execute arbitrary code. We could have a separate service/application that the plugin could communicate with, but that requires writing and maintaining an abstraction layer. The 1.2 version of the Meshtastic API contained breaking changes (which they reached out to me and others about) so I'd have to design and write an abstraction layer that would've worked with both versions of the API. I don't think it's valuable, the signing process is pretty quick but I just haven't had a build that is ready for signing in a while.

There is a new dev build on my Drive link that you can try out, if it is stable I'll send it in for signing.

https://drive.google.com/drive/folders/1appNh7iZ7ir9j0naGD6Ohf_c0iQQfHhJ?usp=sharing

**Comment by HookdomPonix** [comment]
Copy that.  Thank you for the heads up.  As a side note, my primary usage
is tactical.  I am the head instructor for field tactics at a large
training center, but also work in mobile telecom.

I'm doing a testing round with the 4.2.1 build right now paired with your
signed 4.2.1 ATAK.

My Setup:
TTGO T-beam Meshtastic (Setup as Tracker)
TTGO LORA Board (Hooked to ATAK)
Metastatic 1.2.28
Samsung Active Tab 3

Results so far:
1.  Loaded ATAK 4.2.1
2.  Loaded Plugin
3.  Activated plugin
4.  Set my callsign in ATAK
5.  Selected previously paired TTGO LORA radio.
6.  Set a channel (mid range)
7.  Configured Tracker parameters and selected tracker to load (TTGO T-beam)
*8.  I received a ping from the tracker initially, but after that its
definitely strange.  Doesn't seem to want to keep updating.*

I am working on getting a second android device to test this further.
I am getting a lot of errors from the interface, but some delivered packets
as well.  Suspect that it errors out without another device other than the
tracker on the opposite side.
It looks like all settings and options have moved into a sub-menu instead
of being accessible from the main pane of glass?
Will send another update once testing continues.

**Comment by paulmandal** [comment]
Thank you for testing this out! One of the users in the Discord was having an issue where the plugin would not actually set the reporting frequency for Trackers. If you use the Meshtastic app in the Advanced screen you should be able to see/set the reporting frequency.

The settings were moved to make the UI cleaner and use ATAK's built-in settings classes. I was a little unsure about moving some of the settings (i.e. Write to Tracker) but I'm not sure how frequently they would be used in the field -- my thought was that most people would set everything up and then only need to check the status screen after that. I'm open to suggestions here.

**Comment by paulmandal** [comment]
Also I would highly recommend checking out the ATAK Discord, especially the #lora channel, there are a few people testing the plugin there and they can probably give some tips
