### ISSUE TITLE
Not compatible with 4.4.0RC.

### ISSUE THREAD

**Issue by sgofferj** [paulmandal/atak-forwarder#86]
The play store version of ATAK CIV was recently updated to 4.4.0RC and that version reports atak-forwarder as incompatible. 4.3.1 worked fine.

**Comment by pkanischew** [comment]
Can confirm this issue. Had it working with 4.3.1.

**Comment by tim292stro** [comment]
I think this was a broader issue with ATAK-Civ, when I took my update this week, all of my active plug-ins got marked incompatible:
![Screenshot_20210803-145328](https://user-images.githubusercontent.com/45922790/128091545-ae10ca1e-c89c-4557-9b4d-ab65a4ad1ca4.png)

**Comment by sgofferj** [comment]
Yeah, that is because you updated to 4.4.0 and HAMMER and WASP in the play store are also 4.3.1 still. They also need to be updated.

**Comment by tim292stro** [comment]
Just feels like ATAK might be a tad aggressive with version dependency - I doubt they structurally changed the ATAK library API for plug-ins so much in a minor revision that full plug-in recompiles would become necessary is my point.
  
With more plug-ins being developed it might be worth a conversation with the ATAK people to find out if this was a version string issue ("needs >4.3.1" versus "needs 4.3.1") or there might be an improvement to be had in the ATAK base code to not jettison usable code...

**Comment by paulmandal** [comment]
Okay, the plugin has been signed for 4.4.0 and is on the Drive link. Sorry about the delay on that, I've been away on vacation.
