### ISSUE TITLE
Tracker: stale locations presented as fresh in marginal coverage conditions

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#87]
I think I've found an interesting edge case in the stand-alone tracker handling. I'll describe the user perspective first, then the technical side.

I have a Meshtastic tracker moving in and out of my coverage range, in such a way that its (re-)entry point (where I start receiving its messages) is completely different from its exit point (where it loses coverage).

In ATAK, I see the tracker icon moving away from me, then, once out of range, it freezes and starts fading. This is normal and expected behavior. However: when the tracker re-enters coverage hours later (at a different point as discussed), its icon first "comes back to life" **at the old point of last contact** instead of the tracker's actual location. If the coverage remains good, the icon eventually jumps to the correct location, and the tracking continues normally.

Technically, I suspect that this *may be* caused by the NODEINFO packets triggering a CoT update in the plugin. So, if a NODEINFO packet is the first one received after the break, the ensuing CoT update will contain the last recorded location values, per the last POSITION packet received **before** the break.

https://github.com/paulmandal/atak-forwarder/blob/de3a5bbca7187f66f033be20311a0edd8e41d2dd/app/src/main/java/com/paulmandal/atak/forwarder/comm/meshtastic/TrackerEventHandler.java#L52-L60

One possible complicating factor is that NODEINFO packets are physically **smaller** than POSITION packets, and as such, they have a smaller risk of corruption/loss in a marginal coverage situation. This means that, in the scenario above, a NODEINFO packet has a higher than 50% chance of being the first one received.

My suggestion (assuming that my analysis is correct) is to consider **not triggering CoT updates on NODEINFO packets** - either via a boolean argument to function `onTrackerUpdated()` or another way of discriminating between POSITION and NODEINFO updates.

Thank you.

**Comment by paulmandal** [comment]
Fixed by https://github.com/paulmandal/atak-forwarder/pull/90
