### ISSUE TITLE
protobuf RFE: floating point considered harmful :)

### ISSUE THREAD

**Issue by a-f-G-U-C** [paulmandal/atak-forwarder#98]
Floating point fields (and especially double-precision floats) are large, difficult to compress and overhead-y in both layout and operation.

In bandwidth-constrained contexts, like the atak-forwarder protobuf messages where every byte counts, a significant size reduction can be achieved by using exclusively integer fields.

### Example
A latitude or longitude value (currently represented as a 64-bit `double`) can be instead represented using a 32-bit `sfixed32` integer field with a 7-decimal precision (sufficiently accurate to "point to Waldo on a page" *) - and achieve an **8-byte saving** per lat/lon point. 

### Proposal
**Banish all floating-point fields** from the protobuf definition, now and forever, and replace them with conservatively-sized integer fields.
Where possible, the integer values should be used verbatim. However, if the **range** of the chosen format does not fit the range of the variable comfortably, **scaling** and linear **range mapping** rules can be used to force a better range coverage.

*source: https://xkcd.com/2170/

**Comment by paulmandal** [comment]
https://github.com/paulmandal/libcotshrink/pull/14 both addressed here, thanks for the suggestions!
